Update index.md file
gatsbyjs/gatsby-hi pull request #10
Opened 2019-11-08 17:58 UTC by mrmakadia94

translation start in index.md file

2019-11-08 18:00 UTC, arshadkazmi42 commented
@mrmakadia94 You have not translated the complete file. Can you translate the complete file and then re-request for review.
I would be happy to review this once the translation is complete. 
Thanks

2019-11-08 18:02 UTC, mrmakadia94 commented
Hello @arshadkazmi42 
Thanks to connect
i will give you update once i completed the file.

2019-11-08 18:26 UTC, mrmakadia94 commented
Hello @arshadkazmi42 
please check the pull request i just completed the translation of file.

Thanks

2019-11-09 06:02 UTC, arshadkazmi42 requested changes
Great work.
I have added a couple of feedback, once those are fixes, this is good to go

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +आयात EmailCaptureForm from "../../www/src/components/email-capture-form"
`आयात` => `import`

we are not translating code related key words

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +Gatsby React के लिए एक प्रज्वलन तेज़ आधुनिक साइट जनरेटर है।
`Gatsby` => `Gatsby,`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +## शुरू करना
`शुरू करना ` => `शुरू करना`

remove extra space

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +1. [ट्यूटोरियल](/tutorial/): कैसे Gatsby को स्थापित करने और एक परियोजना शुरू करने के लिए चरण-दर-चरण निर्देश: बिना Gatsby या वेब विकास अनुभव के लोगों के लिए लिखा गया है, हालांकि इन सीखने के संसाधनों न
```
कैसे Gatsby को स्थापित करने और एक परियोजना शुरू करने के लिए चरण-दर-चरण निर्देश: बिना Gatsby या वेब विकास अनुभव के लोगों के लिए लिखा गया है, हालांकि इन सीखने के संसाधनों ने सभी कौशल स्तरों के डेवलपर्स की मदद की है।
```
=>
```
Gatsby, को इनस्टॉल करने और एक प्रोजेक्ट सुरु करने के लिए स्टेप-बाई-स्टेप निर्देश: ये उन लोगो के लिए बनाया गया है जिनको Gatsby या वेब विकास का कोई अनुभव नहीं है, हालाँकि इन रिसोर्सेज ने सभी लेवल के डेवेलपर्स की मदद की है।
```

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. [त्वरित प्रारंभ](/docs/quick-start): Gatsby को स्थापित करने और एक नई परियोजना शुरू करने का एक पृष्ठ सारांश।
`त्वरित प्रारंभ` => `क्विक स्टार्ट`

`त्वरित प्रारंभ` sounds a bit complex.

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. [त्वरित प्रारंभ](/docs/quick-start): Gatsby को स्थापित करने और एक नई परियोजना शुरू करने का एक पृष्ठ सारांश।
`स्थापित` => `इनस्टॉल`

please change it for whole file, something like find and replace

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. [त्वरित प्रारंभ](/docs/quick-start): Gatsby को स्थापित करने और एक नई परियोजना शुरू करने का एक पृष्ठ सारांश।
`नई परियोजना` => `नए प्रोजेक्ट`

change `परियोजना` also to `प्रोजेक्ट` in whole file

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. [त्वरित प्रारंभ](/docs/quick-start): Gatsby को स्थापित करने और एक नई परियोजना शुरू करने का एक पृष्ठ सारांश।
`पृष्ठ` => `पेज`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +1. [Recipes](/docs/recipes/): Gatsby गैट्सबी के साथ कुछ विशिष्ट, सामान्य कार्यों को पूरा करने के लिए कुछ त्वरित उत्तर खोजें.
`Gatsby गैट्सबी` => `Gatsby`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +1. [Recipes](/docs/recipes/): Gatsby गैट्सबी के साथ कुछ विशिष्ट, सामान्य कार्यों को पूरा करने के लिए कुछ त्वरित उत्तर खोजें.
`त्वरित` => `क्विक`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +1. [Recipes](/docs/recipes/): Gatsby गैट्सबी के साथ कुछ विशिष्ट, सामान्य कार्यों को पूरा करने के लिए कुछ त्वरित उत्तर खोजें.
`खोजें.` => `खोजें।`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. अपना खुद का साहसिक चुनें और Gatsby डॉक्स के विभिन्न अनुभागों का उपयोग करें.
`साहसिक` => `एडवेंचर`

I am not very sure about this. Any thoughts? Which would be better

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +2. अपना खुद का साहसिक चुनें और Gatsby डॉक्स के विभिन्न अनुभागों का उपयोग करें.
`करें.` => `करें।`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [संदर्भ मार्गदर्शिकाएँ](/docs/guides/): Gatsby के साथ निर्माण सामग्री के आसपास कई अलग-अलग विषयों के बारे में जानें, जैसे सोर्सिंग डेटा, परिनियोजन, और बहुत कुछ.
`संदर्भ मार्गदर्शिकाएँ` => `रिफरेन्स गाइड्स`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [संदर्भ मार्गदर्शिकाएँ](/docs/guides/): Gatsby के साथ निर्माण सामग्री के आसपास कई अलग-अलग विषयों के बारे में जानें, जैसे सोर्सिंग डेटा, परिनियोजन, और बहुत कुछ.
`deployment` => `डिप्लॉयमेंट`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [संदर्भ मार्गदर्शिकाएँ](/docs/guides/): Gatsby के साथ निर्माण सामग्री के आसपास कई अलग-अलग विषयों के बारे में जानें, जैसे सोर्सिंग डेटा, परिनियोजन, और बहुत कुछ.
`कुछ.` => `कुछ।`

Change `.` to `।` everywhere

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby एपीआई संदर्भ](/docs/api-reference/): Gatsby API और कॉन्फ़िगरेशन के बारे में अधिक जानें।
`संदर्भ` => `रिफरेन्स`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [विमोचन और माइग्रेशन](/docs/releases-and-migration/): प्रमुख संस्करणों के बीच प्रवास के लिए रिलीज़ नोट और गाइड खोजें।
`विमोचन` => `रीलीज़ेज़`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [विमोचन और माइग्रेशन](/docs/releases-and-migration/): प्रमुख संस्करणों के बीच प्रवास के लिए रिलीज़ नोट और गाइड खोजें।
`संस्करणों` => `वर्शनस`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [विमोचन और माइग्रेशन](/docs/releases-and-migration/): प्रमुख संस्करणों के बीच प्रवास के लिए रिलीज़ नोट और गाइड खोजें।
`प्रवास` => `माइग्रेशन्स`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [वैचारिक मार्गदर्शक](/docs/conceptual-guide/): Gatsby दृष्टिकोण के उच्च-स्तरीय साक्षात्कार पढ़ें।
`मार्गदर्शक` => `गाइड`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [वैचारिक मार्गदर्शक](/docs/conceptual-guide/): Gatsby दृष्टिकोण के उच्च-स्तरीय साक्षात्कार पढ़ें।
`साक्षात्कार` => `ओवरव्यूज`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby आंतरिक](/docs/gatsby-internals/): पता लगाएं कैसे Gatsby पर्दे के पीछे काम करता है
`आंतरिक` => `इंटरनल्स`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby आंतरिक](/docs/gatsby-internals/): पता लगाएं कैसे Gatsby पर्दे के पीछे काम करता है
`पता लगाएं कैसे Gatsby पर्दे के पीछे काम करता है` => `पता लगाएं Gatsby पर्दे के पीछे कैसे काम करता है।`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby व्यावसायिक रूप से उपयोग करना](/docs/using-gatsby-professionally/):काम पर दूसरों को Gatsby को कैसे समझा जाए, इसके लिए टिप्स और ट्रिक्स सीखें, ताकि आपके पास Gatsby के साथ पेशेवर रूप से काम
`व्यावसायिक` => `प्रोफेश्नल्ली`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby व्यावसायिक रूप से उपयोग करना](/docs/using-gatsby-professionally/):काम पर दूसरों को Gatsby को कैसे समझा जाए, इसके लिए टिप्स और ट्रिक्स सीखें, ताकि आपके पास Gatsby के साथ पेशेवर रूप से काम
`:काम पर दूसरों को Gatsby को कैसे समझा जाए, इसके लिए टिप्स और ट्रिक्स सीखें,` => `: टिप्स और ट्रिक्स सीखें जिससे आप काम पर दूसरों को Gatsby कैसे समझाया जाए,`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [Gatsby व्यावसायिक रूप से उपयोग करना](/docs/using-gatsby-professionally/):काम पर दूसरों को Gatsby को कैसे समझा जाए, इसके लिए टिप्स और ट्रिक्स सीखें, ताकि आपके पास Gatsby के साथ पेशेवर रूप से काम
`पेशेवर` => `प्रोफेशनल`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +3. Gatsby शुरुआत और प्लगइन्स, साथ ही बाहरी सामुदायिक संसाधनों के लिए [पारिस्थितिकी तंत्र](/ecosystem) पुस्तकालयों की जाँच करें।
`पारिस्थितिकी तंत्र` => `इकोसिस्टम`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +3. Gatsby शुरुआत और प्लगइन्स, साथ ही बाहरी सामुदायिक संसाधनों के लिए [पारिस्थितिकी तंत्र](/ecosystem) पुस्तकालयों की जाँच करें।
`पुस्तकालयों` => `लाइब्रेरीज`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +3. Gatsby शुरुआत और प्लगइन्स, साथ ही बाहरी सामुदायिक संसाधनों के लिए [पारिस्थितिकी तंत्र](/ecosystem) पुस्तकालयों की जाँच करें।
`की जाँच करें` => `को देखें`

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +Gatsby समुदाय पर मार्गदर्शिकाएँ, आचार संहिता, और कैसे Gatsby के लिए [योगदान](/contributing) शुरू करने के लिए योगदान करने के लिए योगदान अनुभाग पर जाएँ।
```
Gatsby समुदाय पर मार्गदर्शिकाएँ, आचार संहिता, और कैसे Gatsby के लिए [योगदान](/contributing) शुरू करने के लिए योगदान करने के लिए योगदान अनुभाग पर जाएँ।
```
=>
```
Gatsby कम्युनिटी, अचार सहिंता, और Gatsby में योगदान कैसे सुरु करें इसके लिए [कंट्रिब्यूटिंग](/contributing/) अनुभाग देखें।
```

2019-11-09 06:02 UTC, arshadkazmi42 commented on docs/docs/index.md
>  <EmailCaptureForm signupMessage="Want to keep up with the latest tips &amp; tricks? Subscribe to our newsletter!" />
```
Want to keep up with the latest tips &amp; tricks? Subscribe to our newsletter!
```
=>
```
क्या आप अपने आप को लेटेस्ट टिप्स और ट्रिक्स के साथ अपडेट रखना चाहते हैं? तो हमारे नूस्लेटर सब्सक्राइब करें!
```

2019-11-09 06:33 UTC, mrmakadia94 commented on docs/docs/index.md
> +2. अपना खुद का साहसिक चुनें और Gatsby डॉक्स के विभिन्न अनुभागों का उपयोग करें.
i think एडवेंचर is easy to relate the string

2019-11-09 06:42 UTC, mrmakadia94 commented
Just updated the index.md file as per @arshadkazmi42 given changes.

2019-11-09 07:02 UTC, arshadkazmi42 commented on docs/docs/index.md
> +   - [संदर्भ मार्गदर्शिकाएँ](/docs/guides/): Gatsby के साथ निर्माण सामग्री के आसपास कई अलग-अलग विषयों के बारे में जानें, जैसे सोर्सिंग डेटा, परिनियोजन, और बहुत कुछ.
You missed this one.

Actually this was supposed to be `परिनियोजन` => `डिप्लॉयमेंट`

Sorry! My bad. Can you make changes for this

2019-11-09 07:04 UTC, arshadkazmi42 commented on docs/docs/index.md
> +3. Gatsby शुरुआत और प्लगइन्स, साथ ही बाहरी सामुदायिक संसाधनों के लिए [पारिस्थितिकी तंत्र](/ecosystem) पुस्तकालयों की जाँच करें।
> `पारिस्थितिकी तंत्र` => `इकोसिस्टम`

`इकोसिस्टम तंत्र` 
remove `तंत्र` keep only `इकोसिस्टम`

2019-11-09 07:05 UTC, arshadkazmi42 commented on docs/docs/index.md
>  <EmailCaptureForm signupMessage="Want to keep up with the latest tips &amp; tricks? Subscribe to our newsletter!" />
`नूस्लेटर` => `न्यूज़लेटर`

Can  you change this word, `न्यूज़लेटर` this sounds better

2019-11-09 07:06 UTC, arshadkazmi42 commented
@mrmakadia94 Awesome work with the fixes.
There is two more i have added and 1 you missed. Can you work on those 3 fixes and we will get this merged

2019-11-09 07:22 UTC, mrmakadia94 commented
Thanks @arshadkazmi42  for given updates.

2019-11-09 07:23 UTC, arshadkazmi42 approved these changes
Awesome work 👍 
Thank you for working on it and make changes for the feedbacks

2019-11-09 07:23 UTC, merged

2019-11-09 07:24 UTC, arshadkazmi42 commented
@mrmakadia94 Thank you for this.
You can claim your swag from above url 🎉

2019-11-09 07:47 UTC, mrmakadia94 commented
Thanks for @arshadkazmi42 for guiding and support and Thanks for @gatsbybot providing gift :)

2019-11-09 08:13 UTC, arshadkazmi42 commented
Keep up the awesome work you are doing 👍