Translation of Contributing-To-Gatsby index
gatsbyjs/gatsby-hi pull request #23
Opened 2019-12-21 15:22 UTC by monizb

@arshadkazmi42

2019-12-21 15:50 UTC, arshadkazmi42 commented
@monizb Great work you have been doing.
But we need to get these pages translated first https://github.com/gatsbyjs/gatsby-hi/issues/1
before starting on others.
Also I would suggest, let's get all the open PRs reviewed and merged before you send more PRs

2019-12-21 16:08 UTC, monizb commented
> @monizb Great work you have been doing.
> But we need to get these pages translated first #1
> before starting on others. Please pick pages from that issue
> Also I would suggest, let's get all the open PRs reviewed and merged before you send more PRs

@arshadkazmi42 , great idea will do the same 😀

2020-01-31 16:57 UTC, monizb commented
@arshadkazmi42 Hey, i was wondering if we can get even this closed now since all other PRs are done. Thanks!

2020-01-31 17:26 UTC, arshadkazmi42 commented
sure @monizb I will start reviewing this ASAP

2020-02-02 06:34 UTC, arshadkazmi42 requested changes
Good work.
I have added 2 suggestions, post those fixes its good to go

2020-02-02 06:34 UTC, arshadkazmi42 commented on docs/contributing/index.mdx
> +- [Gatsby की स्टाइल गाइड ](/contributing/gatsby-style-guide/): मे सहयोग देने की कला, जिसको डिटेल्ड रिक्वायरमेंट्स के नाम से भी जाना जाता है जो आपके सहयोग को काम से काम परिवर्तन के साथ भी स्वीकार होने
`मे सहयोग देने की कला, जिसको डिटेल्ड रिक्वायरमेंट्स के नाम से भी जाना जाता है जो आपके सहयोग को काम से काम परिवर्तन के साथ भी स्वीकार होने की संभावना बढ़ा देता है` => `Gatsby में योगदान देने की कला, अर्थात् आपका योगदान संभावित परिवर्तनों के साथ स्वीकार कराने के लिए विस्तृत आवश्यकताएं जो इसे और अधिक संभव बनाती हैं`

How about this?

2020-02-02 06:34 UTC, arshadkazmi42 commented on docs/contributing/index.mdx
> +- [सहयोग कैसे करें](/contributing/how-to-contribute/): कैसे अपने Gatsby.js पर सहयोग देने के अनुभव से सबसे अधिक पाए, GitHub मैनेजमेंट टिप्स सहित, डॉक्स और कोड योगदान के लिए सेटअप निर्देश, और बहुत कुछ
`कैसे अपने Gatsby.js पर सहयोग देने के अनुभव से सबसे अधिक पाए, GitHub मैनेजमेंट टिप्स सहित, डॉक्स और कोड योगदान के लिए सेटअप निर्देश, और बहुत कुछ` => `GitHub प्रबंधन युक्तियों, डॉक्स और कोड योगदानों के लिए सेटअप निर्देश, और बहुत कुछ सहित, अपने Gatsby.js योगदान अनुभव का अधिकतम लाभ कैसे प्राप्त करें`

2020-02-02 07:17 UTC, monizb commented
Done ✅

2020-02-02 07:32 UTC, arshadkazmi42 approved these changes
Awesome work 👏 

Lets get this merged 🎉

2020-02-02 07:32 UTC, merged