tutorial/part-six
gatsbyjs/gatsby-hi pull request #24
Opened 2019-12-27 16:33 UTC by NileshPatel17

2020-01-08 06:36 UTC, NileshPatel17 commented
This PR is ready to be review.

2020-01-08 06:37 UTC, arshadkazmi42 commented
@NileshPatel17 I have been bit busy. I will get to it ASAP

2020-01-08 06:37 UTC, NileshPatel17 commented
OK. No Problem.

2020-01-09 18:05 UTC, arshadkazmi42 requested changes
Great start.

Reviewed till line 36
Also, we should translate line 2 and 7 also

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +पिछले ट्यूटोरियल मे आपने सीखा कि कैसे सोर्स प्लगइन डेटा को Gatsby के डेटा सिस्टम मे लाता हैं। इस ट्यूटोरियल में, आप सीखेंगे कि कैसे ट्रांसफॉर्मर प्लगइन्स अनिर्मित कॉंटेंट को सोर्स प्लगइन्स द्वारा बदल
`मे` => `_मे_`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +पिछले ट्यूटोरियल मे आपने सीखा कि कैसे सोर्स प्लगइन डेटा को Gatsby के डेटा सिस्टम मे लाता हैं। इस ट्यूटोरियल में, आप सीखेंगे कि कैसे ट्रांसफॉर्मर प्लगइन्स अनिर्मित कॉंटेंट को सोर्स प्लगइन्स द्वारा बदल
`बदलता` => `_बदलता_`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +पिछले ट्यूटोरियल मे आपने सीखा कि कैसे सोर्स प्लगइन डेटा को Gatsby के डेटा सिस्टम मे लाता हैं। इस ट्यूटोरियल में, आप सीखेंगे कि कैसे ट्रांसफॉर्मर प्लगइन्स अनिर्मित कॉंटेंट को सोर्स प्लगइन्स द्वारा बदल
`अनिर्मित` => `रॉ`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अक्सर, सोर्स प्लगइन्स से प्राप्त डेटा का फार्मेट वह नहीं होता है जो आप अपनी वेबसाइट बनाने के लिए चाहते हैं। फ़ाइल सिस्टम सोर्स प्लगइन आपके फाइल्स को query करने देता है लेकिन क्या होगा यदि आप फ़ाइलों
`फाइल्स` => `फाइल्स _के बारे में_ डेटा`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अक्सर, सोर्स प्लगइन्स से प्राप्त डेटा का फार्मेट वह नहीं होता है जो आप अपनी वेबसाइट बनाने के लिए चाहते हैं। फ़ाइल सिस्टम सोर्स प्लगइन आपके फाइल्स को query करने देता है लेकिन क्या होगा यदि आप फ़ाइलों
`अंदर` => `_अंदर_`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +इसे संभव बनाने के लिए Gatsby ट्रांसफार्मर प्लगइन्स का समर्थन करता है जो सोर्स प्लगइन्स से raw कॉंटेंट को अधिक उपयोगी मे बदल देता है।
`raw` => `रॉ`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +इसे संभव बनाने के लिए Gatsby ट्रांसफार्मर प्लगइन्स का समर्थन करता है जो सोर्स प्लगइन्स से raw कॉंटेंट को अधिक उपयोगी मे बदल देता है।
`उपयोगी मे बदल` => `उपयोगी _बना_`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +उदाहरण के लिए मार्कडाउन फाइलें। मार्कडाउन लिखना अच्छा है, लेकिन जब आप पेज का निर्माण करते हैं, आप चाहेंगे की मार्कडाउन Html मे परिवर्तित हो जाए।
`Html` => `HTML`

2020-01-09 18:05 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +`src/pages/sweet-pandas-eating-sweets.md` ऐड करें (यह आपका पहला मार्कडाउन ब्लॉग पोस्ट बन जाएगा) और जानें कि कैसे ट्रांसफॉर्मर प्लगइन्स और Graphql का उपयोग करके HTML को _परिवर्तित_ किया जाता है।
`Graphql` => `GraphQL`

2020-01-10 14:20 UTC, NileshPatel17 commented
Done. along with line 2 and 7.

2020-01-10 18:04 UTC, arshadkazmi42 requested changes
Great work.
Added review for rest of the file. It will be good to go post these fixes

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +डेवेलपमेंट सर्वर को रीस्टार्ट करें, फिर GraphiQL को रेफ्रेश (या फिर से खोलें) करें और ऑटो-कंप्लीट को देखे:
`रेफ्रेश` => `रिफ्रेश`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +`allMarkdownRemark` को फिर से सेलेक्ट करे और इसे रन करे जैसा आपने` allFile` के लिए रन किया था। आप हाल ही में आपके द्वारा ऐड किए गए मार्कडाउन फ़ाइल को देखेंगे। अब फीलड्स की छान-बीन करें जो `MarkdownRe
```
` allFile`
```
=>
```
`allFile`
```

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +ठीक है! उम्मीद है, कुछ बेसिक बातें अब समझ मे आने लगी होंगी। सोर्स प्लगइन्स डेटा को Gatsby डेटा सिस्टम मे लाते हैं और _transformer_ प्लगइन्स रॉ कॉंटेंट को स्रोत प्लगइन्स द्वारा _परिवर्तित_ करते हैं। य
`_transformer_` => `_ट्रांसफॉर्मर_`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +ब्लॉग, आप प्रत्येक ब्लॉग पोस्टको इंगित करने वाले फ्रंट पेज पर लिंक की एक सूची के साथ समाप्त करना चाहते हैं। GraphQL से आप मार्कडाउन ब्लॉग पोस्ट की वर्तमान सूची के लिए _query_ कर सकते हैं इसलिए आपको म
`पोस्टको इंगित` => `पोस्ट की तरफ पॉइंट`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +कुछ प्रारंभिक HTML और स्टाइलिंग के साथ Graphql query ऐड करने के लिए निम्नलिखित मे बदलें।
`Graphql` => `GraphQL`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अब बहुत अच्छा लग रहा है! सिवाय ... पोस्ट का क्रम गलत है।
`सिवाय...`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +लेकिन इसे ठीक करना बहुत ही आसान है। किसी प्रकार के कनेक्शन की query करते समय, आप GraphQL query को विभिन्न प्रकार के arguments पास कर सकते हैं। आप नोड को `sort` और `filter` कर सकते हैं, सेट करें कितने
```
की` limit` भी
```
=>
```
की `limit` भी
```

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अपने इंडेक्स पेज की GraphQL query में, `allMarkdownREDIA` को `allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC })` मे बदलें। _Note: `frontmatter` और `date` के बीच ३ अंडरस्कोर हैं।
`allMarkdownREDIA` => `allMarkdownRemark`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अपने इंडेक्स पेज की GraphQL query में, `allMarkdownREDIA` को `allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC })` मे बदलें। _Note: `frontmatter` और `date` के बीच ३ अंडरस्कोर हैं।
`३` => `3`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +अपने इंडेक्स पेज की GraphQL query में, `allMarkdownREDIA` को `allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC })` मे बदलें। _Note: `frontmatter` और `date` के बीच ३ अंडरस्कोर हैं।
`हैं।` => `हैं।_`

2020-01-10 18:04 UTC, arshadkazmi42 commented on docs/tutorial/part-six/index.md
> +आप `src/pages` में React कौम्पोनॅन्टस को रखकर पेज बनाना जारी रख सकते हैं। हालाँकि, आगे आप सीखेंगे कि _programmatically_ _डेटा_ से पेजेज कैसे बनाएं। Gatsby सिर्फ़ static साइट जनरेटर, जैसे फ़ाइलों से प
`अगले ट्यूटोरियल में इसका उपयोग करने के तरीके सीखेंगे [डेटा से programmatically पेजेज बनाना](/tutorial/part-seven/)।` => `अगले [डेटा से programmatically पेजेज बनाना](/tutorial/part-seven/) ट्यूटोरियल में इसका उपयोग करने के तरीके को सीखेंगे ।`

2020-01-11 13:36 UTC, NileshPatel17 commented
Done

2020-01-12 02:41 UTC, arshadkazmi42 approved these changes
Great work 💯 
Thank you for working on all the fixes. 
Let's get this merged

2020-01-12 02:41 UTC, merged