translated
gatsbyjs/gatsby-hi pull request #28
Opened 2020-01-31 16:39 UTC by spielers

translated docs/adding-website-functionality.md

2020-01-31 16:40 UTC, spielers commented
recipes.md translation is on its way. ill try to complete as soon as possible

2020-02-02 07:10 UTC, arshadkazmi42 requested changes
Great work.

i have added some review. Once these are fixed we will get this merged 👍

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +शीर्षक: 404 पेज जोड़ना
`शीर्षक` => `title`

this should not be translated

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +शीर्षक: 404 पेज जोड़ना
`जोड़ना` => `ऐड करना`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +404 पृष्ठ बनाने के लिए एक पेज जिसका पथ regex से मेल खाता बनाने ^\/?404\/?$( /404/, /404, 404/or 404)। बहुधा आप एक प्रतिक्रिया घटक पृष्ठ बनाना चाहेंगे src/pages/404.js .
`पथ` => `पाथ`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +404 पृष्ठ बनाने के लिए एक पेज जिसका पथ regex से मेल खाता बनाने ^\/?404\/?$( /404/, /404, 404/or 404)। बहुधा आप एक प्रतिक्रिया घटक पृष्ठ बनाना चाहेंगे src/pages/404.js .
`404 पृष्ठ बनाने के लिए एक पेज जिसका पथ regex से मेल खाता बनाने ^\/?404\/?$( /404/, /404, 404/or 404)। बहुधा आप एक प्रतिक्रिया घटक पृष्ठ बनाना चाहेंगे src/pages/404.js .` 
=> 
```
404 पेज बनाने के लिए एक पेज बनाये जिसका पाथ ^\/?404\/?$( /404/, /404, 404/or 404) regex से मेल खाता हो। ज़्यादातर आप एक React कौम्पोनॅन्ट पेज बनाना चाहेंगे `src/pages/404.js`।
```

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +404 पृष्ठ बनाने के लिए एक पेज जिसका पथ regex से मेल खाता बनाने ^\/?404\/?$( /404/, /404, 404/or 404)। बहुधा आप एक प्रतिक्रिया घटक पृष्ठ बनाना चाहेंगे src/pages/404.js .
we are not translating React word. Refer [style-guide](https://github.com/gatsbyjs/gatsby-hi/blob/master/style-guide.md) for more info

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +गैट्सबी यह सुनिश्चित करता है कि आपका 404 पेज उतना `404.html`ही स्टैटिक होस्टिंग प्लेटफॉर्म के रूप में बनाया गया है, जो इसे आपके 404 एरर पेज के रूप में उपयोग करने के लिए डिफ़ॉल्ट है। यदि आप अपनी साइट
```
गैट्सबी यह सुनिश्चित करता है कि आपका 404 पेज उतना `404.html`ही स्टैटिक होस्टिंग प्लेटफॉर्म के रूप में बनाया गया है, जो इसे आपके 404 एरर पेज के रूप में उपयोग करने के लिए डिफ़ॉल्ट है।
```
=>
```
Gatsby यह सुनिश्चित करता है कि आपका 404 `404.html` की तरह बना हो क्यूंकि ज़्यादातर स्टेटिक होस्टिंग प्लेटफॉर्म्स इसीको डिफ़ॉल्ट रूप से 404 एरर पेज की तरह इस्तेमाल करते है।
```

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +गैट्सबी यह सुनिश्चित करता है कि आपका 404 पेज उतना `404.html`ही स्टैटिक होस्टिंग प्लेटफॉर्म के रूप में बनाया गया है, जो इसे आपके 404 एरर पेज के रूप में उपयोग करने के लिए डिफ़ॉल्ट है। यदि आप अपनी साइट
`त्रुटियों` => `एर्ररस`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +गैट्सबी यह सुनिश्चित करता है कि आपका 404 पेज उतना `404.html`ही स्टैटिक होस्टिंग प्लेटफॉर्म के रूप में बनाया गया है, जो इसे आपके 404 एरर पेज के रूप में उपयोग करने के लिए डिफ़ॉल्ट है। यदि आप अपनी साइट
`सेवा देने` => `सर्व करने`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +क्योंकि Gatsby डिफ़ॉल्ट रूप से आपके लिए यह पृष्ठ बनाता है, इसलिए इसे आपकी `gatsby-node.js` फ़ाइल में कॉन्फ़िगर करने की कोई आवश्यकता नहीं है ।
`पृष्ठ` => `पेज`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +क्योंकि Gatsby डिफ़ॉल्ट रूप से आपके लिए यह पृष्ठ बनाता है, इसलिए इसे आपकी `gatsby-node.js` फ़ाइल में कॉन्फ़िगर करने की कोई आवश्यकता नहीं है ।
`नहीं है ।` => `नहीं है।`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +प्रयोग करते समय `gatsby develop`, Gatsby एक डिफ़ॉल्ट 404 पृष्ठ का उपयोग करता है जो आपके कस्टम 404 पृष्ठ को ओवरराइड करता है। हालाँकि, आप अभी भी अपने 404 पृष्ठ का पूर्वावलोकन कर सकते हैं "कस्टम 404 पृष
`पृष्ठ` => `पेज`

change this everywhere

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +प्रयोग करते समय `gatsby develop`, Gatsby एक डिफ़ॉल्ट 404 पृष्ठ का उपयोग करता है जो आपके कस्टम 404 पृष्ठ को ओवरराइड करता है। हालाँकि, आप अभी भी अपने 404 पृष्ठ का पूर्वावलोकन कर सकते हैं "कस्टम 404 पृष
`पृष्ठों` => `पेजेज`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +प्रयोग करते समय `gatsby develop`, Gatsby एक डिफ़ॉल्ट 404 पृष्ठ का उपयोग करता है जो आपके कस्टम 404 पृष्ठ को ओवरराइड करता है। हालाँकि, आप अभी भी अपने 404 पृष्ठ का पूर्वावलोकन कर सकते हैं "कस्टम 404 पृष
`को देख सकें` => `को देख सकें।`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +नीचे दिया गया स्क्रीनशॉट Gatsby द्वारा बनाए गए डिफ़ॉल्ट 404 पृष्ठ को दिखाता है।
`पृष्ठ` => `पेज`

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +यह आपकी वेबसाइट के सभी पृष्ठों को भी सूचीबद्ध करता है। "पूर्वावलोकन कस्टम 404" पर क्लिक करना
```
यह आपकी वेबसाइट के सभी पृष्ठों को भी सूचीबद्ध करता है। "पूर्वावलोकन कस्टम 404" पर क्लिक करना 
पृष्ठ "बटन आपको आपके द्वारा बनाए गए 404 पृष्ठ को देखने की अनुमति देगा।
```
=>
```
ये वेब्सीटेस के सारे पेजेज को लिस्ट करता है। "प्रीव्यू कस्टम 404 पेज" बटन को क्लिक करने से ये आपको 404 पेज देखने की अनुमति देगा।
```

2020-02-02 07:10 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +नीचे दिया गया स्क्रीनशॉट कस्टम 404 पृष्ठ दिखाता है।
`पृष्ठ` => `पेज`

2020-02-02 07:54 UTC, spielers commented
docs/docs/add-404-page.md  issues fixed please merge it

2020-02-02 08:17 UTC, spielers commented
merge this page

2020-02-03 04:44 UTC, arshadkazmi42 commented
@spielers This pull request was supposed to be for `add-404-page`

I did review for only that. Also we follow 1 PR per page.

Can you send separate PRs for each page. Also, I will suggest not to create multiple pull requests. Create new pull requests once existing ones are merged.

Once you are done with separating the pages in different PRs. Ping here. I will review and get those merged one by one.

Let me know if you need any help

2020-02-03 04:57 UTC, closed without merging

2020-02-03 05:03 UTC, spielers commented
can you please tell me how can I create a separate pull request for each
page
sorry for the trouble but I am new here.

On Mon, Feb 3, 2020 at 10:14 AM Arshad Kazmi <notifications@github.com>
wrote:

> @spielers <https://github.com/spielers> This pull request was supposed to
> be for add-404-page
>
> I did review for only that. Also we follow 1 PR per page.
>
> Can you send separate PRs for each page. Also, I will suggest not to
> create multiple pull requests. Create new pull requests once existing ones
> are merged.
>
> Once you are done with separating the pages in different PRs. Ping here. I
> will review and get those merged one by one.
>
> Let me know if you need any help
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gatsbyjs/gatsby-hi/pull/28?email_source=notifications&email_token=ALO3RDW6UKPGONSSUBOCMGTRA6OMRA5CNFSM4KOJ45EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKSPDKQ#issuecomment-581235114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALO3RDRTRCB7OB7DSWZXOOLRA6OMRANCNFSM4KOJ45EA>
> .
>