translated page add-404-page
gatsbyjs/gatsby-hi pull request #31
Opened 2020-02-03 05:36 UTC by spielers

please merge this page

2020-02-03 05:37 UTC, spielers commented
sorry for concern I separately added page and translated.

2020-02-07 04:12 UTC, spielers commented
Sir please review this and  merge this .

2020-02-08 03:50 UTC, arshadkazmi42 requested changes
Great work.
Just a couple of fixes and this is good to go

2020-02-08 03:50 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +404 पेज बनाने के लिए एक पेज बनाये जिसका पाथ `^\/?404\/?$` (`/404/`, `/404`, `404/` or `404`) regex से मेल खाता हो। ज़्यादातर आप एक React कौम्पोनॅन्ट पेज बनाना चाहेंगे `src/pages/404.js`।.
```
चाहेंगे `src/pages/404.js`।.
```
=>
```
चाहेंगे `src/pages/404.js`।
```

there is an unwanted dot at the end of the line

2020-02-08 03:50 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +Gatsby यह सुनिश्चित करता है कि आपका 404 `404.html` की तरह बना हो क्यूंकि ज़्यादातर स्टेटिक होस्टिंग प्लेटफॉर्म्स इसीको डिफ़ॉल्ट रूप से 404 एरर पेज की तरह इस्तेमाल करते है। यदि आप अपनी साइट को दूसरे तरी
`आपका 404` => `आपका 404 पेज`

2020-02-08 03:50 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +Gatsby यह सुनिश्चित करता है कि आपका 404 `404.html` की तरह बना हो क्यूंकि ज़्यादातर स्टेटिक होस्टिंग प्लेटफॉर्म्स इसीको डिफ़ॉल्ट रूप से 404 एरर पेज की तरह इस्तेमाल करते है। यदि आप अपनी साइट को दूसरे तरी
`स्थापित` => `सेट-अप`

2020-02-08 03:50 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +प्रयोग करते समय `gatsby develop`, Gatsby एक डिफ़ॉल्ट 404 पेज का उपयोग करता है जो आपके कस्टम 404 पृष्ठ को ओवरराइड करता है। हालाँकि, आप अभी भी अपने 404 पेज का पूर्वावलोकन कर सकते हैं "कस्टम 404 पेज का
`पृष्ठ` => `पेज`

2020-02-08 03:50 UTC, arshadkazmi42 commented on docs/docs/add-404-page.md
> +प्रयोग करते समय `gatsby develop`, Gatsby एक डिफ़ॉल्ट 404 पेज का उपयोग करता है जो आपके कस्टम 404 पृष्ठ को ओवरराइड करता है। हालाँकि, आप अभी भी अपने 404 पेज का पूर्वावलोकन कर सकते हैं "कस्टम 404 पेज का
`पूर्वावलोकन` => `प्रीव्यू`

2020-02-08 11:38 UTC, spielers commented
errors fixed just merge this thing, sir I will start working on other

2020-02-08 17:59 UTC, arshadkazmi42 commented
@spielers Please don't hurry. We want to do the translation, but in the right way. 
I am the only reviewer available. Sometimes it takes some time to get to review.
Hope you understand.

2020-02-08 17:59 UTC, arshadkazmi42 approved these changes
Looks good.
Thank you for working on this.

2020-02-08 18:00 UTC, merged

2020-02-08 18:00 UTC, arshadkazmi42 commented
@spielers Congrats on landing your first PR.
You can claim your swag from above link. Thank you for your contribution