Updated how-to-contribute
gatsbyjs/gatsby-hi pull request #34
Opened 2020-02-08 06:24 UTC by SunitaBhat101

Hey!
I've translated the page. Please let me know if any changes are required!

2020-02-08 18:15 UTC, arshadkazmi42 requested changes
Good start. 👏 

I have added some reviews, we can get this merged once those are fixed

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +शीर्षक: योगदान कैसे करें
`शीर्षक` => `title`

we should not translate this. This will be used while rendering on webpage

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +हम किसी और सभी के लिए मजेदार, आनंददायक और शैक्षिक होने के लिए Gatsby का योगदान चाहते हैं। सभी योगदानों का स्वागत है, जिसमें इश्यूज, नए डॉक्स के साथ-साथ अपडेट और ट्वीक्स, ब्लॉग पोस्ट, कार्यशालाएं, और
`हम किसी और सभी के लिए मजेदार, आनंददायक और शैक्षिक होने के लिए Gatsby का योगदान चाहते हैं।` => `हम किसी और सभी के लिए Gatsby का योगदान को मजेदार, आनंददायक और शैक्षिक बनाना चाहते हैं।`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +हम किसी और सभी के लिए मजेदार, आनंददायक और शैक्षिक होने के लिए Gatsby का योगदान चाहते हैं। सभी योगदानों का स्वागत है, जिसमें इश्यूज, नए डॉक्स के साथ-साथ अपडेट और ट्वीक्स, ब्लॉग पोस्ट, कार्यशालाएं, और
`सभी योगदानों` => `सभी प्रकार के योगदान`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +हम किसी और सभी के लिए मजेदार, आनंददायक और शैक्षिक होने के लिए Gatsby का योगदान चाहते हैं। सभी योगदानों का स्वागत है, जिसमें इश्यूज, नए डॉक्स के साथ-साथ अपडेट और ट्वीक्स, ब्लॉग पोस्ट, कार्यशालाएं, और
`कार्यशालाएं` => `वर्कशॉप्स`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +यदि आप चिंतित हैं या नहीं जानते हैं कि कहां से शुरू करना है, तो हमारे [where to participate](/contributing/where-to-participate/) पृष्ठ देखें। आप ट्विटर पर [Marcy Sutton (@marcysutton)](https://twitt
`where to participate` => `कहाँ भाग लेना है`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +यदि आप चिंतित हैं या नहीं जानते हैं कि कहां से शुरू करना है, तो हमारे [where to participate](/contributing/where-to-participate/) पृष्ठ देखें। आप ट्विटर पर [Marcy Sutton (@marcysutton)](https://twitt
`पृष्ठ` => `पेज`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +यदि आप चिंतित हैं या नहीं जानते हैं कि कहां से शुरू करना है, तो हमारे [where to participate](/contributing/where-to-participate/) पृष्ठ देखें। आप ट्विटर पर [Marcy Sutton (@marcysutton)](https://twitt
```
आप ट्विटर पर [Marcy Sutton (@marcysutton)](https://twitter.com/marcysutton) या [@GatsbyJS](https://twitter.com/gatsbyjs) के सवालों के साथ और Gatsby के किसी भी व्यक्ति तक पहुँच सकते हैं टीम [Discord](https://gatsby.dev/discord) पर। 
```
=>
```
आप अपने सवालों के साथ Twitter पर   [Marcy Sutton (@marcysutton)](https://twitter.com/marcysutton) या [@GatsbyJS](https://twitter.com/gatsbyjs) के पास जा सकते हैं, और  Gatsby टीम के किसी भी  मेंबर से [Discord](https://gatsby.dev/discord) पर।
```

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +Gatsby.js समुदाय को मुफ्त [pair programming sessions](/contributing/pair-programming/) प्रदान करता है, अगर कोई ऐसी चीज है जिस पर आप एक साथ काम करना चाहते हैं। अगर आपके पास योगदान करने या किसी चीज़ को
`pair programming sessions` => `पेअर प्रोग्रामिंग सेशंस`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +## पैर प्रोग्रामिंग
`पैर` => `पेअर`

2020-02-08 18:15 UTC, arshadkazmi42 commented on docs/contributing/how-to-contribute.md
> +Gatsby.js समुदाय को मुफ्त [pair programming sessions](/contributing/pair-programming/) प्रदान करता है, अगर कोई ऐसी चीज है जिस पर आप एक साथ काम करना चाहते हैं। अगर आपके पास योगदान करने या किसी चीज़ को
`जोड़ने` => `ऐड करने`

2020-02-08 18:48 UTC, SunitaBhat101 commented
All done :)

2020-02-09 06:32 UTC, arshadkazmi42 approved these changes
Great 🎉 
Thank you  for working on this 👍

2020-02-09 06:32 UTC, merged

2020-02-09 06:33 UTC, arshadkazmi42 commented
@SunitaBhat101 Congrats on landing your first PR.

You can claim your swag from our swag store. Check the previous comment (by @gatsbybot ) for more information