translated adding page translations.md
gatsbyjs/gatsby-hi pull request #35
Opened 2020-02-08 18:04 UTC by KillMonger1

2020-02-08 18:18 UTC, arshadkazmi42 requested changes
Looks good. 
One small fix and this is good to go

2020-02-08 18:18 UTC, arshadkazmi42 commented on docs/docs/adding-page-transitions.md
> +पेज ट्रांज़िशन उपयोगकर्ताओं को पेजेस के बीच नेविगेट करते समय बेहतर अनुभव देते है। उन्हें अपने Gatsby साइट पर ऐड के कई तरीके हैं।
`पर ऐड के` => `पर ऐड करने के`

2020-02-08 18:35 UTC, KillMonger1 commented
Done

2020-02-09 06:28 UTC, arshadkazmi42 approved these changes
Great work 🎉

2020-02-09 06:28 UTC, merged