translated page add-a-service-worker.md
gatsbyjs/gatsby-hi pull request #40
Opened 2020-02-09 09:02 UTC by spielers

let me know the errors. ill fix asap

2020-02-14 02:51 UTC, arshadkazmi42 requested changes
Added few comments. Its good to go once these are fixed.

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +## service worker क्या है।
`service worker क्या है।` => `सर्विस वर्कर क्या है`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
>  title: Adding a Service Worker
`Adding a Service Worker` => `सर्विस वर्कर ऐड करना`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +service worker एक स्क्रिप्ट है जो आपका ब्राउज़र पृष्ठभूमि में चलता है, एक वेब पेज से अलग होता है, उन सुविधाओं के लिए द्वार खोलता है जिन्हें वेब पेज या उपयोगकर्ता इंटरैक्शन की आवश्यकता नहीं है। वे धब्
`service worker` => `सर्विस वर्कर`

change this everywhere

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +service worker एक स्क्रिप्ट है जो आपका ब्राउज़र पृष्ठभूमि में चलता है, एक वेब पेज से अलग होता है, उन सुविधाओं के लिए द्वार खोलता है जिन्हें वेब पेज या उपयोगकर्ता इंटरैक्शन की आवश्यकता नहीं है। वे धब्
`पृष्ठभूमि` => `बैकग्राउंड`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +service worker एक स्क्रिप्ट है जो आपका ब्राउज़र पृष्ठभूमि में चलता है, एक वेब पेज से अलग होता है, उन सुविधाओं के लिए द्वार खोलता है जिन्हें वेब पेज या उपयोगकर्ता इंटरैक्शन की आवश्यकता नहीं है। वे धब्
`चलता है, एक वेब पेज से अलग होता है,` => `एक वेब पेज से अलग चलता है,`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +service worker एक स्क्रिप्ट है जो आपका ब्राउज़र पृष्ठभूमि में चलता है, एक वेब पेज से अलग होता है, उन सुविधाओं के लिए द्वार खोलता है जिन्हें वेब पेज या उपयोगकर्ता इंटरैक्शन की आवश्यकता नहीं है। वे धब्
`धब्बेदार` => `थोड़े ख़राब`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +## `gatsby-plugin-offline` साथ Gatsby में service workers का उपयोग करना।
`साथ Gatsby में service workers का उपयोग करना।` => `के साथ Gatsby में service workers का उपयोग करना`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +Gatsby आपकी साइट में एक service worker बनाने और लोड करने के लिए अच्छा प्लगइन इंटरफ़ेस प्रदान करता है [gatsby-plugin-offline](https://www.npmjs.com/package/gatsby-plugin-offline).
`service worker` => `सर्विस वर्कर`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +Gatsby आपकी साइट में एक service worker बनाने और लोड करने के लिए अच्छा प्लगइन इंटरफ़ेस प्रदान करता है [gatsby-plugin-offline](https://www.npmjs.com/package/gatsby-plugin-offline).
```
Gatsby आपकी साइट में एक service worker बनाने और लोड करने के लिए अच्छा प्लगइन इंटरफ़ेस प्रदान करता है [gatsby-plugin-offline](https://www.npmjs.com/package/gatsby-plugin-offline).
```
=>
```
Gatsby आपकी साइट [gatsby-plugin-offline](https://www.npmjs.com/package/gatsby-plugin-offline) में एक सर्विस वर्कर बनाने और लोड करने के लिए अच्छा प्लगइन इंटरफ़ेस प्रदान करता है।
```

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +आप इस प्लगइन का उपयोग एक साथ कर सकते हैं [manifest plugin](https://www.npmjs.com/package/gatsby-plugin-manifest). (मैनिफ़ेस्ट प्लगइन के बाद ऑफ़लाइन प्लगइन को सूचीबद्ध करना न भूलें ताकि मेनिफ़ेस्ट फ़ा
```
आप इस प्लगइन का उपयोग एक साथ कर सकते हैं [manifest plugin](https://www.npmjs.com/package/gatsby-plugin-manifest).
```
=>
```
आप इस प्लगइन का उपयोग [मैनिफ़ेस्ट प्लगइन](https://www.npmjs.com/package/gatsby-plugin-manifest) साथ कर सकते हैं।
```

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +##  `gatsby-plugin-offline` को इंस्टॉल करने के लिये
`को इंस्टॉल करने के लिये` => `इनस्टॉल करना`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +इस प्लगइन को अपने `gatsby-config.js`में जोड़ें
```
इस प्लगइन को अपने `gatsby-config.js`में जोड़ें
```
=>
```
इस प्लगइन को अपने `gatsby-config.js` में ऐड करें
```

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
>  - [Service Workers: an Introduction](https://developers.google.com/web/fundamentals/primers/service-workers/)
`Service Workers: an Introduction` => `सर्विस वर्कर: एक परिचय`

2020-02-14 02:51 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
>  - [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
`Service Worker API` => `सर्विस वर्कर API`

2020-02-14 10:30 UTC, spielers commented
changes are done merge this

2020-02-15 07:03 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +## `gatsby-plugin-offline` साथ Gatsby में service workers का उपयोग करना।
```
offline`के
```
=>
```
offline` के
```

add a space before `के`

2020-02-15 07:04 UTC, arshadkazmi42 commented on docs/docs/add-a-service-worker.md
> +आप इस प्लगइन का उपयोग एक साथ कर सकते हैं [manifest plugin](https://www.npmjs.com/package/gatsby-plugin-manifest). (मैनिफ़ेस्ट प्लगइन के बाद ऑफ़लाइन प्लगइन को सूचीबद्ध करना न भूलें ताकि मेनिफ़ेस्ट फ़ा
```
हैं।(मैनिफ़ेस्ट
```
=>
```
हैं। (मैनिफ़ेस्ट
```

add a space before `(मैनिफ़ेस्ट`

2020-02-15 07:05 UTC, arshadkazmi42 requested changes
Good work. there is two small fixes required

2020-02-15 07:09 UTC, spielers commented
changes have done

2020-02-15 07:13 UTC, arshadkazmi42 approved these changes
🎉

2020-02-15 07:13 UTC, merged