translated api-files-gatsby-node.md
gatsbyjs/gatsby-hi pull request #55
Opened 2020-03-05 17:58 UTC by noisefilter19

2020-03-07 15:18 UTC, monizb commented
@arshadkazmi42 Should i take this for a first look?

2020-03-10 06:09 UTC, arshadkazmi42 commented
@monizb sure go ahea

2020-03-31 05:11 UTC, monizb requested changes
@noisefilter19 Thanks for the translation, there is a small error after which we should be good to go!

2020-03-31 05:11 UTC, monizb commented on docs/docs/api-files-gatsby-node.md
> +हर Gatsby नोड API passes a [नोड एपीआई सहायकों का एक सेट](/docs/node-api-helpers/). ये आपको रिपोर्टिंग जैसे कई तरीकों तक पहुँचने देते हैं, या नए पेज बनाने जैसे कार्य करने देता है ।
```suggestion
हर Gatsby नोड API एक [नोड एपीआई सहायकों का एक सेट] पास करता है (/docs/node-api-helpers/)। ये आपको कई तरीकों तक पहुँचने देते हैं जैसे रिपोर्टिंग, नए पेज बनाने जैसे कार्य करने देता है ।
```

2020-05-27 05:11 UTC, arshadkazmi42 commented
@noisefilter19 any updates here?

2020-05-27 05:23 UTC, noisefilter19 commented
Sorry, was caught up with some work.
Have made the changes

2020-07-08 04:08 UTC, arshadkazmi42 approved these changes
👍 

Thank you for working on this

2020-07-08 04:09 UTC, arshadkazmi42 commented
@monizb can you approve this PR. So i can merge it

2020-08-27 07:33 UTC, merged