Translated docs/AB testing to hindi
gatsbyjs/gatsby-hi pull request #58
Opened 2020-04-20 22:15 UTC by Aayush-1999

2020-05-08 08:59 UTC, arshadkazmi42 requested changes
Great work 👍 

Added couple of feedbacks, once those are fixed this will be good to go

2020-05-08 08:59 UTC, arshadkazmi42 commented on docs/docs/ab-testing.md
> +A / B या विभाजन परीक्षण तब होता है जब आप किसी वेबसाइट में परीक्षण परिवर्तन करते हैं। मान लीजिए कि आपके पास दो बटन हैं: एक हरा "अभी खरीदें!" बटन और एक लाल "अब खरीदें!" बटन। आप यह पता लगाना चाहते हैं क
`A / B` => `A/B`

2020-05-08 08:59 UTC, arshadkazmi42 commented on docs/docs/ab-testing.md
> +अवलोकन: true
`अवलोकन ` => `ओवरव्यू`

2020-05-08 08:59 UTC, arshadkazmi42 commented on docs/docs/ab-testing.md
> +A / B परीक्षण आपकी वेबसाइट पर क्या काम करता है, यह पता लगाने के लिए एक डेटा-चालित तरीका है, और यह प्रभावी तरीके से सुधार करने का तरीका निर्धारित करने का एक शानदार तरीका है। A / B परीक्षण दशकों से आसप
`A / B` => `A/B`

change this everywhere

2020-05-08 08:59 UTC, arshadkazmi42 commented on docs/docs/ab-testing.md
> +यह कहा जा रहा है, A / B परीक्षण सॉफ्टवेयर निषेधात्मक रूप से महंगा हो सकता है। कुछ प्लेटफॉर्म हजारों प्रति माह में चल सकते हैं। Gatsby के साथ A / B परीक्षण आयोजित करने के मुख्य लाभ प्रदर्शन और मूल्य ह
`A / B` => `A/B`

change this everywhere

2020-05-10 12:41 UTC, Aayush-1999 commented
@arshadkazmi42 Changes done. Plz review the doc.

2020-05-27 05:04 UTC, arshadkazmi42 approved these changes
great work 👍

2020-05-27 05:04 UTC, merged