translated to hindi
gatsbyjs/gatsby-hi pull request #60
Opened 2020-05-28 12:23 UTC by kaioshin20

2020-07-08 04:25 UTC, arshadkazmi42 requested changes
added some feedback.
we can get this fixed and this will be good to be merged

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +शीर्षक: खोज जोड़ना
`खोज जोड़ना` => `सर्च ऐड करना`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +शीर्षक: खोज जोड़ना
`शीर्षक` => `title`

do not translate this, this will be used by to read title from the file

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +ओवरव्यू: true
`ओवरव्यू` => `overview`

do not translate this, this will be used by to read overview from the file

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +## साइट खोज अवलोकन
`खोज अवलोकन` => `सर्च ओवरव्यू`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +अपनी Gatsby वेबसाइट में खोज जोड़ने के चरणों से गुजरने से पहले, किसी वेबसाइट पर खोज जोड़ने के लिए आवश्यक घटकों की जाँच करें।
`घटकों` => `कौम्पोनॅन्टस`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +## साइट खोज घटक
`खोज` => `सर्च`

change this everywhere

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +## साइट खोज घटक
`घटक` => `कौम्पोनॅन्ट`

change this everywhere

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +### खोज सूचकांक
`खोज` => `सर्च`

change this everywhere

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +खोज सूचकांक आपके डेटा की एक प्रति खोज-अनुकूल प्रारूप में संग्रहीत होती है। खोज क्वेरी निष्पादित करते समय गति और प्रदर्शन को अनुकूलित करने के लिए एक सूचकांक है। सूचकांक के बिना, प्रत्येक खोज को आपकी स
Translation too complex. Can you revisit this and simplify it in simple words

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +खोज इंजन एक खोज क्वेरी लेता है, इसे खोज इंडेक्स के माध्यम से चलाता है, और किसी भी मिलान दस्तावेज़ को वापस करता है।
`मिलान` => `मैचिंग`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +## अपनी साइट पर खोज जोड़ना
`जोड़ना` => `ऐड करना`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +अब जब आप तीन आवश्यक घटक जानते हैं, तो आपके Gatsby-संचालित साइट पर खोज को जोड़ने के लिए कुछ तरीके हैं।
`संचालित` => `पावर्ड`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +अब जब आप तीन आवश्यक घटक जानते हैं, तो आपके Gatsby-संचालित साइट पर खोज को जोड़ने के लिए कुछ तरीके हैं।
`जोड़ने` => `ऐड करने`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +एक खुला स्रोत खोज इंजन का उपयोग करना हमेशा मुफ़्त होता है और आपको अपनी साइट के लिए ऑफ़लाइन खोज सक्षम करने की अनुमति देता है। ध्यान दें कि आपको ऑफ़लाइन खोज से सावधान रहने की आवश्यकता है क्योंकि पूरे ख
`सूचकांक` => `इंडेक्स`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
Remove line break at line 44

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +अन्य पुस्तकालयों के लिए, आप संयोजन का उपयोग कर सकते हैं : [`onCreateNode`](/docs/node-apis/#onCreateNode), [`setFieldsOnGraphQLNodeType`](/docs/node-apis/#setFieldsOnGraphQLNodeType) तथा [`sourceNode
`पुस्तकालयों` => `लाइब्रेरीज`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +अन्य पुस्तकालयों के लिए, आप संयोजन का उपयोग कर सकते हैं : [`onCreateNode`](/docs/node-apis/#onCreateNode), [`setFieldsOnGraphQLNodeType`](/docs/node-apis/#setFieldsOnGraphQLNodeType) तथा [`sourceNode
`ग्राफकॉल` => `GraphQL`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +खोज सूचकांक के निर्माण और इसे Gatsby की डेटा परत में शामिल करने के बाद, आपको उपयोगकर्ता को अपनी वेबसाइट खोजने की अनुमति देने की आवश्यकता होगी। यह आमतौर पर खोज क्वेरी पर कब्जा करने के लिए एक पाठ इनपुट
revisit the translation

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +एक अन्य विकल्प बाहरी खोज इंजन का उपयोग करना है। यह समाधान बहुत अधिक स्केलेबल है क्योंकि आपकी साइट पर आगंतुकों को आपकी साइट पर खोज करने के लिए आपके संपूर्ण खोज इंडेक्स (जो आपकी साइट बढ़ने पर बहुत बड़े
`आगंतुकों ` => `विसिटोर्स`

2020-07-08 04:25 UTC, arshadkazmi42 commented on docs/docs/adding-search.md
> +एलिटिक्स खोज में खोज के लिए कई React घटक लाइब्रेरी हैं। https://github.com/appbaseio/reactivesearch
`एलिटिक्स खोज` => `Elasticsearch`

2020-07-16 11:58 UTC, kaioshin20 commented
@arshadkazmi42 I have done the requested changes. Kindly review my pr

2020-08-27 07:32 UTC, arshadkazmi42 approved these changes
Good work.

Thanks

2020-08-27 07:32 UTC, merged