Translated index.md file inside tutorial folder
gatsbyjs/gatsby-hi pull request #7
Opened 2019-11-04 18:29 UTC by SatyaRF

2019-11-05 06:35 UTC, arshadkazmi42 requested changes
Great work.
Added some review, can  you work on those fixes

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby में आपका स्वागत है! हम खुश हैं कि आप यहां हो। इस ट्यूटोरियल का लक्ष्य स्टार्टर टेम्पलेट का उपयोग करके अपनी पहली गैट्सबी साइट की स्थापना और तैनाती के माध्यम से मार्गदर्शन करना है। जब हम उस प्रक
`गैट्सबी` => `Gatsby`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby में आपका स्वागत है! हम खुश हैं कि आप यहां हो। इस ट्यूटोरियल का लक्ष्य स्टार्टर टेम्पलेट का उपयोग करके अपनी पहली गैट्सबी साइट की स्थापना और तैनाती के माध्यम से मार्गदर्शन करना है। जब हम उस प्रक
`तैनाती के माध्यम से मार्गदर्शन` => `डेप्लॉय`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby में आपका स्वागत है! हम खुश हैं कि आप यहां हो। इस ट्यूटोरियल का लक्ष्य स्टार्टर टेम्पलेट का उपयोग करके अपनी पहली गैट्सबी साइट की स्थापना और तैनाती के माध्यम से मार्गदर्शन करना है। जब हम उस प्रक
`जब हम उस प्रक्रिया से गुजरते हैं तो हम कुछ और सामान्य वेब विकास विषय पेश करते हैं और एक Gatsby साइट की अंतर्निहित संरचना पर चलते हैं।` 
=> 
`जैसे जैसे हम इस टुटोरिअल में आगे बढ़ेंगे, हम कुछ और वेब डेवलपमेंट विषय से परिचय कराएँगे और एक गैट्सबी साइट की अंतर्निहित संरचना पर जाएंगे।`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +> पूर्ण ट्यूटोरियल का उद्देश्य अधिक वेब विकास अनुभव (अभी तक!) के बिना लोगों के लिए जितना संभव हो उतना सुलभ होना चाहिए - विशेषज्ञ होने की आवश्यकता नहीं है। यदि आप सीधे कोड पर कूदना पसंद करते हैं तो चर
`कोड पर कूदना` => `कोड करना`

how about this?

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +> पूर्ण ट्यूटोरियल का उद्देश्य अधिक वेब विकास अनुभव (अभी तक!) के बिना लोगों के लिए जितना संभव हो उतना सुलभ होना चाहिए - विशेषज्ञ होने की आवश्यकता नहीं है। यदि आप सीधे कोड पर कूदना पसंद करते हैं तो चर
`चरण-दर-चरण` => `स्टेप-बाय-स्टेप`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +> पूर्ण ट्यूटोरियल का उद्देश्य अधिक वेब विकास अनुभव (अभी तक!) के बिना लोगों के लिए जितना संभव हो उतना सुलभ होना चाहिए - विशेषज्ञ होने की आवश्यकता नहीं है। यदि आप सीधे कोड पर कूदना पसंद करते हैं तो चर
Line break needed at line 7

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +0.  [अपने विकास का वातावरण तैयार करें](/tutorial/part-zero/): हम आपको Gatsby को शक्ति प्रदान करने वाली मुख्य तकनीकों से परिचित कराएँगे और आपके विकास के वातावरण को स्थापित करने के माध्यम से मार्गदर्शन
`करने के माध्यम से मार्गदर्शन करेंगे` => `करने में आपका मार्गदर्शन करेंगे`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +1.  [Gatsby बिल्डिंग ब्लॉक्स के बारे में जानें](/tutorial/part-one/): नई परियोजनाएं शुरू करना विकास करना और साइटों को तैनात करना।
`नई परियोजनाएं शुरू करना विकास करना और साइटों को तैनात करना।` => `नए प्रोजेक्टस शुरू करना, विकास करना, और साइटों को डेप्लॉय करना`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +1.  [Gatsby बिल्डिंग ब्लॉक्स के बारे में जानें](/tutorial/part-one/): नई परियोजनाएं शुरू करना विकास करना और साइटों को तैनात करना।
`Gatsby के बिल्डिंग ब्लॉक्स के बारे में जानें` => `Gatsby बिल्डिंग ब्लॉक्स के बारे में जानें`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +2.  [Gatsby में CSS का उपयोग करने का परिचय](/tutorial/part-two/): Typography.js और CSS मॉड्यूल जैसे libraries का अन्वेषण करें।
`का अन्वेषण` => `को एक्स्प्लोर`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +3.  [Gatsby में नेस्टेड लेआउट बनाना](/tutorial/part-three/): लेआउट आपकी साइट के ऐसे अनुभाग हैं जिनका पुन: उपयोग कई पृष्ठों जैसे हेडर और फ़ूटर में किया जाता है।
`उपयोग कई पृष्ठों जैसे हेडर और फ़ूटर में किया जाता है` => `उपयोग कई पृष्ठों  में किया जाता है जैसे हेडर और फ़ूटर`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +इन इंटरमीडिएट ट्यूटोरियल्स में आप सीखेंगे कि ग्राफ़िक्स के साथ अपने गैट्सबी साइट में लगभग कहीं से भी डेटा कैसे खींच सकते हैं।
`खींच` => `पुल्ल कर`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +4.  [एक ब्लॉग में डेटा के लिए क्वेरी](/tutorial/part-four/): एक ब्लॉग बनाएं और अपनी साइट शीर्षक को ब्लॉग हेडर में खींचने के लिए एक GraphQL क्वेरी का उपयोग करें।
`खींचने` => `पुल्ल करने`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +5.  [सस्रोत प्लगइन्स और क्वेरी किये गए डेटा की रेंडरिंग ](/tutorial/part-five/): अपनी साइट में मार्कडाउन ब्लॉग पोस्ट खींचने के लिए स्रोत प्लगइन का उपयोग करें और ब्लॉग पोस्ट की सूची के साथ एक इंडेक्स
`सस्रोत` => `सोर्स`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +5.  [सस्रोत प्लगइन्स और क्वेरी किये गए डेटा की रेंडरिंग ](/tutorial/part-five/): अपनी साइट में मार्कडाउन ब्लॉग पोस्ट खींचने के लिए स्रोत प्लगइन का उपयोग करें और ब्लॉग पोस्ट की सूची के साथ एक इंडेक्स
`खींचने` => `पुल्ल करने`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +5.  [सस्रोत प्लगइन्स और क्वेरी किये गए डेटा की रेंडरिंग ](/tutorial/part-five/): अपनी साइट में मार्कडाउन ब्लॉग पोस्ट खींचने के लिए स्रोत प्लगइन का उपयोग करें और ब्लॉग पोस्ट की सूची के साथ एक इंडेक्स
`स्रोत` => `सोर्स`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +6.  [ट्रांसफार्मर पप्लगइन्स](/tutorial/part-six/): अपने मार्कडाउन ब्लॉग पोस्ट को उस रूप में बदलने के लिए एक ट्रांसफॉर्मर प्लगइन का उपयोग करें जिसे ब्लॉग रेंडर कर सकता है।
`पप्लगइन्स` => `प्लगइन्स`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +7.  [प्रोग्रामेटिक रूप से डेटा से पेज बनाना](/tutorial/part-seven/): अपने ब्लॉग पोस्ट के लिए प्रोग्राम के द्वारा पृष्ठों का सेट बनाना सीखें।
`पृष्ठों` => `पेजेस`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +8.  [लाइव होने के लिए एक साइट को तैयार करना](/tutorial/part-eight/): अपनी साइट को प्रदर्शन ऑडिट और एक्सेसिबिलिटी SEO और अधिक के लिए सर्वोत्तम प्रथाओं के बारे में जानें।
`अपनी साइट को प्रदर्शन ऑडिट` => `अपनी साइट को परफॉरमेंस के लिए ऑडिट करना सीखें`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +8.  [लाइव होने के लिए एक साइट को तैयार करना](/tutorial/part-eight/): अपनी साइट को प्रदर्शन ऑडिट और एक्सेसिबिलिटी SEO और अधिक के लिए सर्वोत्तम प्रथाओं के बारे में जानें।
`एक्सेसिबिलिटी SEO और अधिक के लिए सर्वोत्तम प्रथाओं के बारे में जानें` => `अक्सेसिब्लिटी, SEO, और अधिक चीज़ों की बेहतरीन कार्यप्रणाली के बारे में जानें`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby थीम आपकी डिफ़ॉल्ट कॉन्फ़िगरेशन (साझा कार्यक्षमता डेटा सोर्सिंग डिज़ाइन) को आपकी साइट से बाहर और एक इंस्टॉल किए जाने योग्य पैकेज में सार करती है।
`साझा कार्यक्षमता डेटा सोर्सिंग डिज़ाइन` => `शेयर्ड फ़ंक्शनैलिटी, डेटा सोर्सिंग, डिज़ाइन`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby थीम आपकी डिफ़ॉल्ट कॉन्फ़िगरेशन (साझा कार्यक्षमता डेटा सोर्सिंग डिज़ाइन) को आपकी साइट से बाहर और एक इंस्टॉल किए जाने योग्य पैकेज में सार करती है।
`सार` = >`एबसट्रैक्ट`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +इसका मतलब यह है कि कॉन्फ़िगरेशन और कार्यक्षमता सीधे आपकी परियोजना में नहीं लिखी गई है बल्कि संस्करण केंद्रीय रूप से प्रबंधित और एक निर्भरता के रूप में स्थापित है। आप मूल रूप से एक विषय को अपडेट कर सक
`कार्यक्षमता` => `फ़ंक्शनैलिटी`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +इसका मतलब यह है कि कॉन्फ़िगरेशन और कार्यक्षमता सीधे आपकी परियोजना में नहीं लिखी गई है बल्कि संस्करण केंद्रीय रूप से प्रबंधित और एक निर्भरता के रूप में स्थापित है। आप मूल रूप से एक विषय को अपडेट कर सक
`परियोजना` => `प्रोजेक्ट`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +इसका मतलब यह है कि कॉन्फ़िगरेशन और कार्यक्षमता सीधे आपकी परियोजना में नहीं लिखी गई है बल्कि संस्करण केंद्रीय रूप से प्रबंधित और एक निर्भरता के रूप में स्थापित है। आप मूल रूप से एक विषय को अपडेट कर सक
`बल्कि संस्करण केंद्रीय रूप से प्रबंधित और एक निर्भरता के रूप में स्थापित है` => `बल्कि वर्शन, सेंट्रली मैनेज  और डिपेंडेंसी की तरह इनस्टॉल की गयी है`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +इसका मतलब यह है कि कॉन्फ़िगरेशन और कार्यक्षमता सीधे आपकी परियोजना में नहीं लिखी गई है बल्कि संस्करण केंद्रीय रूप से प्रबंधित और एक निर्भरता के रूप में स्थापित है। आप मूल रूप से एक विषय को अपडेट कर सक
`आप मूल रूप से एक विषय को अपडेट कर सकते हैं एक साथ विषयों की रचना कर सकते हैं और यहां तक कि दूसरे के लिए एक संगत विषय को स्वैप कर सकते हैं`
=>
`आप मूल रूप से एक थीम को अपडेट, कई थीम्स को आपस में कंपोज़, और एक कम्पेटिबल थीम के बदले दूसरे को इस्तेमाल कर सकते हैं`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +थीम के उपयोग और निर्माण के बारे में अधिक जानें [Gatsby थीम ट्यूटोरियल](/tutorial/theme-tutorials/).
`थीम के उपयोग और निर्माण के बारे में अधिक जानें [Gatsby थीम ट्यूटोरियल](/tutorial/theme-tutorials/).` 
=>
`[Gatsby थीम ट्यूटोरियल](/tutorial/theme-tutorials/) से थीम के उपयोग और निर्माण के बारे में अधिक जानें।`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +## अतिरिक्त ट्यूटोरियल
`अतिरिक्त` => `एडिशनल`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby के लिए कई उपयोग के मामले हैं जिनमें से कुछ आप सीखते समय ध्यान केंद्रित रखने के लिए ट्यूटोरियल के पहले सेट में शामिल नहीं हैं। Gatsby का अतिरिक्त ट्यूटोरियल अनुभाग संसाधनों का एक संग्रह है जो द
`Gatsby के लिए कई उपयोग के मामले हैं जिनमें से कुछ आप सीखते समय ध्यान केंद्रित रखने के लिए ट्यूटोरियल के पहले सेट में शामिल नहीं हैं। Gatsby का अतिरिक्त ट्यूटोरियल अनुभाग संसाधनों का एक संग्रह है जो दिखाता है कि कैसे और भी अधिक Gatsby कार्यों को चरण-दर-चरण पूरा किया जाए जैसे कि छवियों और CMS सामग्री के लिए स्रोत प्लगइन्स का उपयोग करना।`
=>
`Gatsby के लिए काफी यूस केसेस हैं, जिनमें से कुछ पहले टुटोरिअल्स सेट में नहीं डाले गए हैं ताकि अाप सिखने पर ज़्यादा ध्यान दे सकें। Gatsby एडिशनल टुटोरिअल अनुभाग में रिसोर्सेज के कलेक्शन हैं जो आपको मदद करेगा की  कैसे और ज़्यादा  Gatsby कार्य स्टेप-बाई-स्टेप पूरा कर सकते हैं, जैसे की इमेजेज और CMS कंटेंट के लिए सोर्स प्लगिन्स का इस्तेमाल करना।`

2019-11-05 06:35 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +और गहराई में जाये [अतिरिक्त Gatsby ट्यूटोरियल](/tutorial/additional-tutorials/).
`और गहराई में जाये [अतिरिक्त Gatsby ट्यूटोरियल](/tutorial/additional-tutorials/).` => `[एडिशनल गैट्सबी टुटोरिअल](/tutorial/additional-tutorials/) की और गहराई में जाएँ।`

2019-11-07 17:22 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby में आपका स्वागत है! हम खुश हैं कि आप यहां हो। इस ट्यूटोरियल का लक्ष्य स्टार्टर टेम्पलेट का उपयोग करके अपनी पहली गैट्सबी साइट की स्थापना और तैनाती के माध्यम से मार्गदर्शन करना है। जब हम उस प्रक
I can see this in few more places, can you update this in whole file? (Something like find and replace)

2019-11-07 17:27 UTC, arshadkazmi42 commented on docs/tutorial/index.md
> +Gatsby थीम आपकी डिफ़ॉल्ट कॉन्फ़िगरेशन (साझा कार्यक्षमता डेटा सोर्सिंग डिज़ाइन) को आपकी साइट से बाहर और एक इंस्टॉल किए जाने योग्य पैकेज में सार करती है।
You missed commas for this, can you recheck once, aslo `शेयर्ड` spelling is wrong

2019-11-07 17:31 UTC, arshadkazmi42 commented
@SatyaRF There are two feedbacks left, once those are fixed, this will be good to get merged

2019-11-07 17:47 UTC, arshadkazmi42 approved these changes
Awesome work ❤️ 
Let's get this merged 🎉

2019-11-07 17:47 UTC, merged

2019-11-07 17:49 UTC, arshadkazmi42 commented
@SatyaRF You can collect your swag from above link 🎉

2019-11-07 17:53 UTC, SatyaRF commented
Thanks @arshadkazmi42 for the support.