Hindi Translation for quick-start
gatsbyjs/gatsby-hi pull request #9
Opened 2019-11-07 17:51 UTC by akramkazmi71

Hindi translation for docs/quick-start. issue #1

2019-11-07 17:55 UTC, arshadkazmi42 requested changes
@akramkazmi71 Thank you for working on this, but looks like you have created a new file for this in place of editing the existing one.
You need to move this file to `docs/` folder, currently its in `docs/docs/`

2019-11-07 18:23 UTC, arshadkazmi42 requested changes
Great work.
Added few feedbacks.
It will be good to go, once those fixes are check in 👍

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +यह क्विक स्टार्ट मध्यवर्ती से उन्नत डेवलपर्स के लिये है| गैट्सबी के एक विनम्र परिचय के लिए, [हमारे ट्यूटोरियल देखें](/tutorial/)!
`मध्यवर्ती` => `इंटरमीडिएट`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +यह क्विक स्टार्ट मध्यवर्ती से उन्नत डेवलपर्स के लिये है| गैट्सबी के एक विनम्र परिचय के लिए, [हमारे ट्यूटोरियल देखें](/tutorial/)!
`उन्नत` => `एडवांस्ड`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +यह क्विक स्टार्ट मध्यवर्ती से उन्नत डेवलपर्स के लिये है| गैट्सबी के एक विनम्र परिचय के लिए, [हमारे ट्यूटोरियल देखें](/tutorial/)!
`है|` => `है।`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +## गैट्सबी सीएलआई का उपयोग
`गैट्सबी` => `Gatsby`

We are not translating `Gatsby` word, Can you find and replace this in whole file

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +## गैट्सबी सीएलआई का उपयोग
`सीएलआई का उपयोग` => `सीएलआई का उपयोग करें`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +  lessonTitle="गैट्सबी के साथ तुरंत शुरुआत करें: कमांड लाइन से गैट्सबी साइट बनाएँ, विकसित और निर्माण करें"
`विकसित` => `विकसित करें`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +**नोट**: इस वीडियो में `npx` का उपयोग किया गया है, जो पहले स्थापित किए बिना npm पैकेज को निष्पादित करने के लिए एक उपकरण है। अपने कंप्यूटर पर गैट्सबी-सीएलआई को स्थापित करने के बाद कमांड `npx gatsby ne
`स्थापित` => `इनस्टॉल`

Change this everywhere, (find & replace)

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +**नोट**: इस वीडियो में `npx` का उपयोग किया गया है, जो पहले स्थापित किए बिना npm पैकेज को निष्पादित करने के लिए एक उपकरण है। अपने कंप्यूटर पर गैट्सबी-सीएलआई को स्थापित करने के बाद कमांड `npx gatsby ne
`निष्पादित` => `एग्ज़ीक्यूट`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +**नोट**: इस वीडियो में `npx` का उपयोग किया गया है, जो पहले स्थापित किए बिना npm पैकेज को निष्पादित करने के लिए एक उपकरण है। अपने कंप्यूटर पर गैट्सबी-सीएलआई को स्थापित करने के बाद कमांड `npx gatsby ne
`उपकरण` => `टूल`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +**नोट**: इस वीडियो में `npx` का उपयोग किया गया है, जो पहले स्थापित किए बिना npm पैकेज को निष्पादित करने के लिए एक उपकरण है। अपने कंप्यूटर पर गैट्सबी-सीएलआई को स्थापित करने के बाद कमांड `npx gatsby ne
`गैट्सबी` => `Gatsby`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +### गैट्सबी सीएलआई स्थापित करें।
`गैट्सबी` => `Gatsby`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +### गैट्सबी सीएलआई स्थापित करें।
`स्थापित` => `इनस्टॉल`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +### डेवलपमेंट सर्वर शुरू करें|
`करें|` => `करें।`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी डिफ़ॉल्ट रूप से हॉट-रीलोडिंग डेवलपमेंट वातावरण शुरू करेगा `localhost:8000`.
```
गैट्सबी डिफ़ॉल्ट रूप से हॉट-रीलोडिंग डेवलपमेंट वातावरण शुरू करेगा `localhost:8000`.
```
=> 
```
Gatsby एक हॉट-रीलोडिंग डेवलपमेंट एनवायरनमेंट सुरु करेगा जो की डिफ़ॉल्ट रूप से `localhost:8000` पर एक्सेसिबल रहेगाें।
```

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +`Src / pages` में जावास्क्रिप्ट पेज को एडिट करने का प्रयास करें। बचाया गए परिवर्तन ब्राउज़र में पुनः लोड होंगे।
```
`Src / pages`
```
=>
```
`src/pages`
```

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +`Src / pages` में जावास्क्रिप्ट पेज को एडिट करने का प्रयास करें। बचाया गए परिवर्तन ब्राउज़र में पुनः लोड होंगे।
`बचाया गए परिवर्तन ब्राउज़र में पुनः लोड होंगे` => `सेव किये गए बदलाव ब्राउज़र में लाइव पुनः लोड होंगे`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी स्थैतिक HTML और प्रति मार्ग जावास्क्रिप्ट कोड बंडलों का निर्माण करते हुए, आपकी साइट के लिए एक अनुकूलित उत्पादन निर्माण करेगा।
`गैट्सबी` => `Gatsby`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी स्थैतिक HTML और प्रति मार्ग जावास्क्रिप्ट कोड बंडलों का निर्माण करते हुए, आपकी साइट के लिए एक अनुकूलित उत्पादन निर्माण करेगा।
`स्थैतिक` => `इसटैटिक`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी स्थैतिक HTML और प्रति मार्ग जावास्क्रिप्ट कोड बंडलों का निर्माण करते हुए, आपकी साइट के लिए एक अनुकूलित उत्पादन निर्माण करेगा।
`अनुकूलित उत्पादन निर्माण करेगा` => `ऑप्टीमाइज़्ड प्रोडक्शन बिल्ड का निर्माण करेगा`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +### उत्पादन का निर्माण स्थानीय स्तर पर करें।
`उत्पादन का निर्माण स्थानीय स्तर पर करें।` => `प्रोडक्शन बिल्ड को लोकल पर सर्व करें।`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी आपकी निर्मित साइट के परीक्षण के लिए एक स्थानीय HTML सर्वर शुरू करता है। इस कमांड का उपयोग करने से पहले `gatsby build` का उपयोग करके अपनी साइट बनाना याद रखें।
`गैट्सबी` => `Gatsby`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी आपकी निर्मित साइट के परीक्षण के लिए एक स्थानीय HTML सर्वर शुरू करता है। इस कमांड का उपयोग करने से पहले `gatsby build` का उपयोग करके अपनी साइट बनाना याद रखें।
`निर्मित` => `बनी हुई`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी आपकी निर्मित साइट के परीक्षण के लिए एक स्थानीय HTML सर्वर शुरू करता है। इस कमांड का उपयोग करने से पहले `gatsby build` का उपयोग करके अपनी साइट बनाना याद रखें।
`स्थानीय` => `लोकल`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +### सीएलआई कमांड के लिए डॉक्यूमेंटेशन
`डॉक्यूमेंटेशन` => `एक्सेस डॉक्यूमेंटेशन`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +सीएलआई कमांड के लिए विस्तृत दस्तावेज देखने के लिए, टर्मिनल में `gatsby --help` चलाएं।
`कमांड के लिए विस्तृत दस्तावेज` => `कमांड के विस्तृत डॉक्यूमेंटेशन`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +विशिष्ट आदेशों के लिए, `gatsby COMMAND_NAME --help` रन करें, उदाहरण: `gatsby new --help`|
`आदेशों` => `कमांड्स`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +विशिष्ट आदेशों के लिए, `gatsby COMMAND_NAME --help` रन करें, उदाहरण: `gatsby new --help`|
`रन करें` => `चलाएं`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +विशिष्ट आदेशों के लिए, `gatsby COMMAND_NAME --help` रन करें, उदाहरण: `gatsby new --help`|
`|` => `।`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी सीएलआई के बारे में अधिक जानकारी के लिए, [सीएलआई संदर्भ](/docs/gatsby-cli/) देखें|
`गैट्सबी` => `Gatsby`

2019-11-07 18:23 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी सीएलआई के बारे में अधिक जानकारी के लिए, [सीएलआई संदर्भ](/docs/gatsby-cli/) देखें|
`|` => `।`

2019-11-08 08:59 UTC, akramkazmi71 commented
Updated the doc as specified.

2019-11-08 12:06 UTC, arshadkazmi42 commented on docs/docs/quick-start.md
> +गैट्सबी डिफ़ॉल्ट रूप से हॉट-रीलोडिंग डेवलपमेंट वातावरण शुरू करेगा `localhost:8000`.
`रहेगाें` => `रहेगा`

2019-11-08 12:10 UTC, akramkazmi71 commented on docs/docs/quick-start.md
> +गैट्सबी डिफ़ॉल्ट रूप से हॉट-रीलोडिंग डेवलपमेंट वातावरण शुरू करेगा `localhost:8000`.
resolved.

2019-11-08 12:13 UTC, arshadkazmi42 approved these changes
Great. Thank you 👍

2019-11-08 12:13 UTC, merged

2019-11-08 12:14 UTC, arshadkazmi42 commented
@akramkazmi71 You can grab your swag from above link. 🎉 
Thank you for taking time and working on this translation

2020-04-21 20:24 UTC, imrishabh18 commented
Hey, I am a beginner. Can i contribute to translate any doc ?

2020-04-22 02:54 UTC, monizb commented
Hello @imrishabh18 ! Welcome to Gatsby. Yes, you can contribute to any doc which is not yet taken by anyone. Please head over to https://github.com/gatsbyjs/gatsby-hi/issues/1 and comment the name of the doc you want to translate and then one of us will assign them to you :)